---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: groups
  description: A collection of Groups
spec:
  targets:
    - ./groups/*.yml

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: users
  description: A collection of Users
spec:
  targets:
    - ./users/*.yml
