server:
  port: 9090

spring:
  application:
    name: odai

  ai:
    ollama:
      chat:
        options:
          model: mistral
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        dimensions: 768
        index-type: hnsw

  threads:
    virtual:
      enabled: true
