spring:
  application:
    name: mousike

  ai:
    model:
      chat: mistral
      embedding: mistral
    mistralai:
      chat:
        options:
          model: mistral-medium-latest
      embedding:
        options:
          model: mistral-embed
    openai:
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
    vectorstore:
      pgvector:
        dimensions: 1024
        index-type: hnsw

  servlet:
    multipart:
      max-file-size: 10MB

  threads:
    virtual:
      enabled: true

logging:
  level:
    org.atmosphere: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"

arconia:
  dev:
    services:
      phoenix:
        image-name: arizephoenix/phoenix:version-12.9-nonroot
  otel:
    metrics:
      exporter:
        interval: 5s

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.thomasvitale.mousike
  pnpm:
    enable: true
