spring:
  application:
    name: mousike

  http:
    client:
      connect-timeout: 30s
      read-timeout: 60s

  ai:
    model:
      chat: mistral
    chat:
      client:
        observations:
          include-input: true
      observations:
        include-prompt: true
        include-completion: true
    mistralai:
      chat:
        options:
          model: mistral-small-latest
      embedding:
        options:
          model: mistral-embed
    openai:
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      observations:
        include-query-response: true
      pgvector:
        dimensions: 1024
        index-type: hnsw

  servlet:
    multipart:
      max-file-size: 10MB

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

arconia:
  dev:
    services:
      postgresql:
        image-name: pgvector/pgvector:pg17
  otel:
    metrics:
      interval: 5s

vaadin:
  launch-browser: true
