server:
  port: 8080

spring:
  application:
    name: mousike

  http:
    client:
      connect-timeout: 30s
      read-timeout: 60s

  ai:
    chat:
      client:
        observations:
          include-input: true
      observations:
        include-prompt: true
        include-completion: true
    openai:
      chat:
        options:
          model: gpt-4o
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      observations:
        include-query-response: true
      pgvector:
        dimensions: 1536
        index-type: hnsw

  servlet:
    multipart:
      max-file-size: 10MB

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      service.name: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,dev.hilla,com.thomasvitale.mousike
