---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - github.com/ThomasVitale/document-assistant/config/workload.yml?ref=main

patches:
  - path: patch-workload.yml
    target:
      kind: Workload
