---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - https://raw.githubusercontent.com/ThomasVitale/document-assistant/main/config/workload.yml

patches:
  - path: patch-workload.yml
    target:
      kind: Workload
