---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - https://github.com/ThomasVitale/question-answering-rag/blob/main/config/workload.yml

patches:
  - path: patch-workload.yml
    target:
      kind: Workload
