---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: postgresql
  namespace: postgresql
spec:
  inputResources:
    - name: pg
      ref:
        apiVersion: v1
        kind: Secret
        name: pg-cluster-app
  template:
    type: servicebinding.io/postgresql
    data:
      username: $(.pg.data.username)
      password: $(.pg.data.password)
      jdbc-url: $(.pg.data.jdbc-uri)
    stringData:
      type: "postgresql"

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: postgresql
  namespace: postgresql
spec:
  toNamespaces:
    - apps

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: postgresql
  namespace: apps
spec:
  fromNamespace: postgresql

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: open-ai
  namespace: kadras-system
spec:
  inputResources:
    - name: openai
      ref:
        apiVersion: v1
        kind: Secret
        name: openai-secret
  template:
    type: servicebinding.io/open-ai
    data:
      api-key: $(.openai.data.api-key) 
    stringData:
      type: "open-ai"
      uri: "https://api.openai.com"

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: open-ai
  namespace: kadras-system
spec:
  toNamespaces:
    - default

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: open-ai
  namespace: default
spec:
  fromNamespace: kadras-system
