platform:
  profile: run
  
  additional_packages:
    - crossplane
    - developer-portal
    - gitops-configurer
    - service-binding
    - postgresql-operator
  
  ingress:
    domain: cloud.thomasvitale.dev
    issuer:
      type: letsencrypt
      email: security@kadras.io

contour:
  certificates:
    useCertManager: true

developer_portal:
  backstage:
    replicas: 2
    appConfig:
      catalog:
        locations:
          - type: url
            target: https://github.com/kadras-io/kadras-developer-portal/blob/main/demo-catalog/organizations/organization-kadras.yml
            rules:
              - allow: [User, Group, Location]
          - type: url
            target: https://github.com/kadras-io/kadras-developer-portal/blob/main/demo-catalog/templates/templates.yml
            rules:
              - allow: [Template, Location]
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    host: backstage.cloud.thomasvitale.dev

flux:
  optional_components:
    helm_controller: true

gitops_configurer:
  type: flux-kustomization
  git:
    url: https://github.com/ThomasVitale/concerto-for-java-and-ai
    path: platform/gitops/clusters/cloud

workspace_provisioner:
  namespaces:
    - name: apps
    - name: default
    - name: observability
